language: rust
sudo: false
rust:
  - nightly-2018-04-03
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
notifications:
  slack:
    rooms:
      - parkas-team:0twCBUENCd9xqXn4DEVm0gEX
    on_success: change
    on_failure: change
