var ALIASES = {};
ALIASES['expandconfig'] = {};
ALIASES['parse_event_log'] = {};
ALIASES['telamon'] = {};
ALIASES['telamon_capi'] = {};
ALIASES['telamon_gen'] = {};
ALIASES['telamon_gen_test'] = {};
ALIASES['telamon_kernels'] = {};
ALIASES['telamon_utils'] = {};
