[package]
authors = ["Ulysse Beaugnon <ulysse.beaugnon@ens.fr>"]
build = "build.rs"
name = "telamon"
readme = "README.md"
version = "0.2.0"

[replace]
"rustlex:0.3.3" = { path = "lib/rustlex" }

[workspace]
members = [
    "telamon-gen",
    "telamon-utils",
    "telamon-gen/cc_tests",
]

#[[bench]]
#harness = false
#name = "mppa"

[[bin]]
name = "cuda-characterize"
path = "tools/cuda_characterize/main.rs"
required-features = ["cuda"]

[[bin]]
name = "cache-bench"
path = "tools/cuda_characterize/cache_main.rs"
required-features = ["cuda"]

[[bin]]
name = "bench-perf-model"
path = "tools/bench_perf_model/main.rs"
required-features = ["cuda"]

[[example]]
name = "main"
path = "examples/main.rs"
required-features = ["cuda"]

[[example]]
name = "sgemm"
path = "examples/sgemm.rs"
required-features = ["cuda"]

[[example]]
name = "sgemm_low"
path = "examples/sgemm_low.rs"
required-features = ["cuda"]

[build-dependencies]
gcc = "0.3.54"

[build-dependencies.telamon-gen]
path = "telamon-gen"

[dependencies]
config = "0.8.0"
crossbeam = "0.3.2"
data_structure_traits = "0.1.8"
env_logger = "0.5.5"
errno = "0.2.3"
getopts = "0.2.17"
immut_list = "0.1.0"
interval-heap = "0.0.5"
ipc-channel = "0.10.0"
itertools = "0.7.7"
lazy_static = "1.0.0"
libc = "0.2.39"
linked-list = "0.0.3"
log = "0.4.1"
matches = "0.1.6"
num = "0.1.42"
parking_lot = "0.5.4"
pbr = "1.0.0"
prctl = "1.0.0"
prettytable-rs = "0.6.7"
rand = "0.4.2"
rayon = "1.0.0"
regex = "0.2.9"
rustc-serialize = "0.3.24"
std-semaphore = "0.1.0"
tokio = "0.1"
# TODO(cleanup): use an official version when futures-2.0 is released.
tokio-timer = { git = "https://github.com/ulysseB/tokio-timer.git" }
futures = "0.2.0-beta"

[dependencies.telamon-utils]
path = "telamon-utils"

[dev-dependencies]
gcc = "0.3.54"
tempdir = "0.3.6"

[features]
cuda = []
default = []
format_exh = []
mppa = []

[profile.bench]
panic = "abort"

[profile.release]
panic = "abort"
