 - add_parallel (max, [+])
	- thread_overhead = 0; thread_overhead.add_parallel(f64)
	- dim_overhead = f64; dim_overhead.add_parallel(f64)
	  (*min* goes into `pressure` in repeat_and_add_bottlenecks)
	- hw_pressure = <sym>; overhead = <sym>; hw_pressure.add_parallel(overhead)
 - add_sequential (+, [+])
	- dim_pressure = <sym>; dim_pressure.add_sequential(f64)
	  (goes into `hw_pressure` in add_parallel)
 - repeat_parallel (., [*])
	- overhead = f64; overhead.repeat_parallel(size - 1)
	  (goes into `overhead` in add_parallel)
 - repeat_and_add_bottlenecks (., [+])
	- pressure = <sym>; pressure.repeat_and_add_bottlenecks(<min_num_threads>, init_pressure)
 - repeat_sequential (*, [*])
	- dim_pressure = f64; dim_pressure.repeat_sequential(size)
	  (goes into `dim_pressure` in add_sequential)
 - multiply (*, [*])
 - minimize (min, [min])
 - min (min, [min])
