(function() {var implementors = {};
implementors["telamon"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"telamon/model/struct.HwPressure.html\" title=\"struct telamon::model::HwPressure\">HwPressure</a>&gt; for <a class=\"struct\" href=\"telamon/device/cuda/struct.InstDesc.html\" title=\"struct telamon::device::cuda::InstDesc\">InstDesc</a>",synthetic:false,types:["telamon::device::cuda::gpu::InstDesc"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"telamon/ir/struct.DimId.html\" title=\"struct telamon::ir::DimId\">DimId</a>",synthetic:false,types:["telamon::ir::dimension::DimId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"telamon/ir/struct.InstId.html\" title=\"struct telamon::ir::InstId\">InstId</a>",synthetic:false,types:["telamon::ir::instruction::InstId"]},];
implementors["telamon_capi"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"telamon/ir/function/struct.Function.html\" title=\"struct telamon::ir::function::Function\">Function</a>&lt;'static, <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.unit.html\">()</a>&gt;&gt; for <a class=\"struct\" href=\"telamon_capi/ir/struct.Function.html\" title=\"struct telamon_capi::ir::Function\">Function</a>",synthetic:false,types:["telamon_capi::ir::Function"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
