(function() {var implementors = {};
implementors["telamon"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"telamon/model/struct.HwPressure.html\" title=\"struct telamon::model::HwPressure\">HwPressure</a>&gt; for <a class=\"struct\" href=\"telamon/device/cuda/struct.InstDesc.html\" title=\"struct telamon::device::cuda::InstDesc\">InstDesc</a>",synthetic:false,types:["telamon::device::cuda::gpu::InstDesc"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"telamon/ir/struct.DimId.html\" title=\"struct telamon::ir::DimId\">DimId</a>",synthetic:false,types:["telamon::ir::dimension::DimId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"telamon/ir/struct.InstId.html\" title=\"struct telamon::ir::InstId\">InstId</a>",synthetic:false,types:["telamon::ir::instruction::InstId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"telamon/ir/mem/struct.InternalId.html\" title=\"struct telamon::ir::mem::InternalId\">InternalId</a>",synthetic:false,types:["telamon::ir::mem::InternalId"]},];
implementors["telamon_capi"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"telamon/ir/function/struct.Function.html\" title=\"struct telamon::ir::function::Function\">Function</a>&lt;'static, <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.unit.html\">()</a>&gt;&gt; for <a class=\"struct\" href=\"telamon_capi/ir/struct.Function.html\" title=\"struct telamon_capi::ir::Function\">Function</a>",synthetic:false,types:["telamon_capi::ir::Function"]},];
implementors["telamon_utils"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;T&gt;&gt; for <a class=\"enum\" href=\"telamon_utils/sequence/enum.Sequence.html\" title=\"enum telamon_utils::sequence::Sequence\">Sequence</a>&lt;T&gt;",synthetic:false,types:["telamon_utils::sequence::Sequence"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
