(function() {var implementors = {};
implementors["tokio"] = [{text:"impl <a class=\"trait\" href=\"tokio/prelude/future/trait.Future.html\" title=\"trait tokio::prelude::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio/net/struct.ConnectFuture.html\" title=\"struct tokio::net::ConnectFuture\">ConnectFuture</a>",synthetic:false,types:["tokio::net::tcp::stream::ConnectFuture"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"tokio/prelude/future/trait.Future.html\" title=\"trait tokio::prelude::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio/net/struct.SendDgram.html\" title=\"struct tokio::net::SendDgram\">SendDgram</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">[</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt;,&nbsp;</span>",synthetic:false,types:["tokio::net::udp::send_dgram::SendDgram"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"tokio/prelude/future/trait.Future.html\" title=\"trait tokio::prelude::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio/net/struct.RecvDgram.html\" title=\"struct tokio::net::RecvDgram\">RecvDgram</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsMut.html\" title=\"trait core::convert::AsMut\">AsMut</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">[</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt;,&nbsp;</span>",synthetic:false,types:["tokio::net::udp::recv_dgram::RecvDgram"]},{text:"impl <a class=\"trait\" href=\"tokio/prelude/future/trait.Future.html\" title=\"trait tokio::prelude::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio/runtime/struct.Shutdown.html\" title=\"struct tokio::runtime::Shutdown\">Shutdown</a>",synthetic:false,types:["tokio::runtime::Shutdown"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
